name: flutter_chatapp_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  lottie: ^2.2.0
  introduction_screen: ^3.1.4
  avatar_glow: ^2.0.2
  emoji_picker_flutter: ^1.5.2
  get_storage: ^2.0.3
  cloud_firestore: ^4.3.1
  intl: ^0.17.0
  image_picker: ^0.8.6
  firebase_storage: ^11.0.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/logo/
  - assets/lottie/

